//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StringResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string AdAbout {
            get {
                return ResourceManager.GetString("AdAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string AddAd {
            get {
                return ResourceManager.GetString("AddAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string AdDate {
            get {
                return ResourceManager.GetString("AdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление изображений к объявлению.
        /// </summary>
        internal static string AddImagesForAd {
            get {
                return ResourceManager.GetString("AddImagesForAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string admin_Add {
            get {
                return ResourceManager.GetString("admin_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string admin_Back {
            get {
                return ResourceManager.GetString("admin_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться на сайт.
        /// </summary>
        internal static string admin_backToSite {
            get {
                return ResourceManager.GetString("admin_backToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string admin_Cancel {
            get {
                return ResourceManager.GetString("admin_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Города.
        /// </summary>
        internal static string admin_Cities {
            get {
                return ResourceManager.GetString("admin_Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть города.
        /// </summary>
        internal static string admin_Cities_View {
            get {
                return ResourceManager.GetString("admin_Cities_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя города.
        /// </summary>
        internal static string admin_City_Example {
            get {
                return ResourceManager.GetString("admin_City_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        internal static string admin_Comment {
            get {
                return ResourceManager.GetString("admin_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактный e-mail сайта.
        /// </summary>
        internal static string admin_ContactEmail {
            get {
                return ResourceManager.GetString("admin_ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страны.
        /// </summary>
        internal static string admin_Countries {
            get {
                return ResourceManager.GetString("admin_Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактируем страны.
        /// </summary>
        internal static string admin_Countries_Edit {
            get {
                return ResourceManager.GetString("admin_Countries_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string admin_Delete {
            get {
                return ResourceManager.GetString("admin_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать категорию.
        /// </summary>
        internal static string admin_EditCategory {
            get {
                return ResourceManager.GetString("admin_EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать страницу.
        /// </summary>
        internal static string admin_EditPage {
            get {
                return ResourceManager.GetString("admin_EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        internal static string admin_EditPage_Parent {
            get {
                return ResourceManager.GetString("admin_EditPage_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория, включающая данную страницу.
        /// </summary>
        internal static string admin_EditPage_ParentNote {
            get {
                return ResourceManager.GetString("admin_EditPage_ParentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать текст.
        /// </summary>
        internal static string admin_editText {
            get {
                return ResourceManager.GetString("admin_editText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактируем пользователя.
        /// </summary>
        internal static string admin_editUser {
            get {
                return ResourceManager.GetString("admin_editUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактируем список форм собственности.
        /// </summary>
        internal static string admin_FormaSobstvennosti_Edit {
            get {
                return ResourceManager.GetString("admin_FormaSobstvennosti_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите данные новой записи.
        /// </summary>
        internal static string admin_help_enterItem {
            get {
                return ResourceManager.GetString("admin_help_enterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списки.
        /// </summary>
        internal static string admin_Lists {
            get {
                return ResourceManager.GetString("admin_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string admin_Login {
            get {
                return ResourceManager.GetString("admin_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переместить ниже.
        /// </summary>
        internal static string admin_MoveDown {
            get {
                return ResourceManager.GetString("admin_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переместить выше.
        /// </summary>
        internal static string admin_MoveUP {
            get {
                return ResourceManager.GetString("admin_MoveUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string admin_Name {
            get {
                return ResourceManager.GetString("admin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая запись.
        /// </summary>
        internal static string admin_new {
            get {
                return ResourceManager.GetString("admin_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет ни одной записи.
        /// </summary>
        internal static string admin_No_Items {
            get {
                return ResourceManager.GetString("admin_No_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string admin_Pas {
            get {
                return ResourceManager.GetString("admin_Pas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль.
        /// </summary>
        internal static string admin_Role {
            get {
                return ResourceManager.GetString("admin_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        internal static string admin_role_Administrator {
            get {
                return ResourceManager.GetString("admin_role_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент.
        /// </summary>
        internal static string admin_role_User {
            get {
                return ResourceManager.GetString("admin_role_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string admin_Save {
            get {
                return ResourceManager.GetString("admin_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки сайта.
        /// </summary>
        internal static string admin_Settings {
            get {
                return ResourceManager.GetString("admin_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP - логин.
        /// </summary>
        internal static string admin_SMTPlogin {
            get {
                return ResourceManager.GetString("admin_SMTPlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP - пароль.
        /// </summary>
        internal static string admin_SMTPpassword {
            get {
                return ResourceManager.GetString("admin_SMTPpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP - порт.
        /// </summary>
        internal static string admin_SMTPport {
            get {
                return ResourceManager.GetString("admin_SMTPport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP - сервер.
        /// </summary>
        internal static string admin_SMTPserver {
            get {
                return ResourceManager.GetString("admin_SMTPserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон.
        /// </summary>
        internal static string admin_Template {
            get {
                return ResourceManager.GetString("admin_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string admin_Title {
            get {
                return ResourceManager.GetString("admin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        internal static string admin_Type {
            get {
                return ResourceManager.GetString("admin_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string admin_Users {
            get {
                return ResourceManager.GetString("admin_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполняйте поля паролей если надо сменить пароль или когда создаете новую учетную запись.
        /// </summary>
        internal static string admin_User_PwdNote {
            get {
                return ResourceManager.GetString("admin_User_PwdNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить и выслать письмо о регистрации.
        /// </summary>
        internal static string admin_User_SaveUserWithRegEmail {
            get {
                return ResourceManager.GetString("admin_User_SaveUserWithRegEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать SMTP - авторизацию.
        /// </summary>
        internal static string admin_UseSMTPAuth {
            get {
                return ResourceManager.GetString("admin_UseSMTPAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значения.
        /// </summary>
        internal static string admin_Values {
            get {
                return ResourceManager.GetString("admin_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактируем список видов деятельности.
        /// </summary>
        internal static string admin_VidiDeyatelnosti_Edit {
            get {
                return ResourceManager.GetString("admin_VidiDeyatelnosti_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видимый.
        /// </summary>
        internal static string admin_Visible {
            get {
                return ResourceManager.GetString("admin_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видимая.
        /// </summary>
        internal static string admin_VisibleF {
            get {
                return ResourceManager.GetString("admin_VisibleF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидать*.
        /// </summary>
        internal static string admin_Wate {
            get {
                return ResourceManager.GetString("admin_Wate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидает.
        /// </summary>
        internal static string admin_Wates {
            get {
                return ResourceManager.GetString("admin_Wates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание! Если ожидает, то не активен!.
        /// </summary>
        internal static string admin_Wate_Tooltip {
            get {
                return ResourceManager.GetString("admin_Wate_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string AdName {
            get {
                return ResourceManager.GetString("AdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объявления.
        /// </summary>
        internal static string AdsInCategory {
            get {
                return ResourceManager.GetString("AdsInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление объявления.
        /// </summary>
        internal static string AdToCategory {
            get {
                return ResourceManager.GetString("AdToCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить еще объявление.
        /// </summary>
        internal static string ad_addMore {
            get {
                return ResourceManager.GetString("ad_addMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спросить.
        /// </summary>
        internal static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсы валют.
        /// </summary>
        internal static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработка сайта -.
        /// </summary>
        internal static string Developed_by {
            get {
                return ResourceManager.GetString("Developed_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название и текст редактируются администратором..
        /// </summary>
        internal static string EditedByAdmin {
            get {
                return ResourceManager.GetString("EditedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верны почта/пароль или ваша учетная запить не прошела активацию администратором..
        /// </summary>
        internal static string Error_AuthorizationFailed {
            get {
                return ResourceManager.GetString("Error_AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка. Попробуйте действие позже..
        /// </summary>
        internal static string Error_General {
            get {
                return ResourceManager.GetString("Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка. Попробуйте, пожалуйста, еще раз..
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответ.
        /// </summary>
        internal static string faq_Answer {
            get {
                return ResourceManager.GetString("faq_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос.
        /// </summary>
        internal static string faq_Question {
            get {
                return ResourceManager.GetString("faq_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string FieldError {
            get {
                return ResourceManager.GetString("FieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложенный файл.
        /// </summary>
        internal static string form_Contact_Attachment {
            get {
                return ResourceManager.GetString("form_Contact_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Е-mail.
        /// </summary>
        internal static string form_Contact_Email {
            get {
                return ResourceManager.GetString("form_Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        internal static string form_Contact_Message {
            get {
                return ResourceManager.GetString("form_Contact_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string form_Contact_Name {
            get {
                return ResourceManager.GetString("form_Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Послать.
        /// </summary>
        internal static string form_Contact_Send {
            get {
                return ResourceManager.GetString("form_Contact_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратная связь.
        /// </summary>
        internal static string form_Contact_us {
            get {
                return ResourceManager.GetString("form_Contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активен.
        /// </summary>
        internal static string form_Reg_Active {
            get {
                return ResourceManager.GetString("form_Reg_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название фирмы.
        /// </summary>
        internal static string form_Reg_CompanyName {
            get {
                return ResourceManager.GetString("form_Reg_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        internal static string form_Reg_ConfirmPwd {
            get {
                return ResourceManager.GetString("form_Reg_ConfirmPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        internal static string form_Reg_Country {
            get {
                return ResourceManager.GetString("form_Reg_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при создании учетной записи. Попробуйте, пожалуйста, еще раз..
        /// </summary>
        internal static string form_Reg_CreateError {
            get {
                return ResourceManager.GetString("form_Reg_CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        internal static string form_Reg_Email {
            get {
                return ResourceManager.GetString("form_Reg_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учетная запись с этим адресом электронной почты уже существует. Возможно, она еще не активирована администратором..
        /// </summary>
        internal static string form_Reg_EmailExistsError {
            get {
                return ResourceManager.GetString("form_Reg_EmailExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты не соответствует формату. Если в указанном вами адресе нет ошибки, свяжитесь с администратором через Контакты..
        /// </summary>
        internal static string form_Reg_EmailInvalid {
            get {
                return ResourceManager.GetString("form_Reg_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное имя.
        /// </summary>
        internal static string form_Reg_FIO {
            get {
                return ResourceManager.GetString("form_Reg_FIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После регистрации ваша учетная запись должна быть активирована администратором. До активации вы не сможете использовать учетную запись для входа. Об активации вы будете уведомлены письмом..
        /// </summary>
        internal static string form_Reg_Note {
            get {
                return ResourceManager.GetString("form_Reg_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string form_Reg_Pwd {
            get {
                return ResourceManager.GetString("form_Reg_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        internal static string form_Reg_PwdMismatch {
            get {
                return ResourceManager.GetString("form_Reg_PwdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        internal static string form_Reg_Region {
            get {
                return ResourceManager.GetString("form_Reg_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string form_Reg_Submit {
            get {
                return ResourceManager.GetString("form_Reg_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы зарегистрировались.&lt;br /&gt;Далее ваша учетная запись должна быть активирована администратором. До активации вы не сможете использовать учетную запись для входа. Об активации вы будете уведомлены письмом..
        /// </summary>
        internal static string form_Reg_Success {
            get {
                return ResourceManager.GetString("form_Reg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, вы зарегистрировались на сайте.&lt;br /&gt;&lt;br /&gt;Далее ваша учетная запись должна быть активирована администратором. &lt;br /&gt;До активации вы не сможете использовать учетную запись для входа. Об активации вы будете уведомлены отдельным письмом..
        /// </summary>
        internal static string form_Reg_Success_email {
            get {
                return ResourceManager.GetString("form_Reg_Success_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        internal static string form_Reg_TelNum {
            get {
                return ResourceManager.GetString("form_Reg_TelNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string form_Reg_Title {
            get {
                return ResourceManager.GetString("form_Reg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться на главную страницу.
        /// </summary>
        internal static string go_to_main_page {
            get {
                return ResourceManager.GetString("go_to_main_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string link_registration {
            get {
                return ResourceManager.GetString("link_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отправить письмо. Попробуйте, пожалуйста, еще раз..
        /// </summary>
        internal static string Mail_sending_failed {
            get {
                return ResourceManager.GetString("Mail_sending_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при отправке письма..
        /// </summary>
        internal static string message_EmailSendingFail {
            get {
                return ResourceManager.GetString("message_EmailSendingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким логином уже существует..
        /// </summary>
        internal static string message_LoginExists {
            get {
                return ResourceManager.GetString("message_LoginExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение регистрации.
        /// </summary>
        internal static string message_RegistrationConfirmSubj {
            get {
                return ResourceManager.GetString("message_RegistrationConfirmSubj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объявление успешно сохранено. Оно появится на сайте после проверки администратором..
        /// </summary>
        internal static string Msg_AdAdded {
            get {
                return ResourceManager.GetString("Msg_AdAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив новостей.
        /// </summary>
        internal static string NewsArchive {
            get {
                return ResourceManager.GetString("NewsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        internal static string news_more {
            get {
                return ResourceManager.GetString("news_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои данные.
        /// </summary>
        internal static string Page_Title_MyData {
            get {
                return ResourceManager.GetString("Page_Title_MyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серьги для прокалывания мочки уха.
        /// </summary>
        internal static string Page_title_ProductsList {
            get {
                return ResourceManager.GetString("Page_title_ProductsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        internal static string pge_Change {
            get {
                return ResourceManager.GetString("pge_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты или пароль не верен.
        /// </summary>
        internal static string pge_Login_InvalidCredentialsMsg {
            get {
                return ResourceManager.GetString("pge_Login_InvalidCredentialsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string pge_Login_LogIn {
            get {
                return ResourceManager.GetString("pge_Login_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string pge_Login_Pass {
            get {
                return ResourceManager.GetString("pge_Login_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        internal static string pge_Login_PasswordRequired {
            get {
                return ResourceManager.GetString("pge_Login_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        internal static string pge_Login_RecoverPwd {
            get {
                return ResourceManager.GetString("pge_Login_RecoverPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to запомнить.
        /// </summary>
        internal static string pge_Login_RememberMe {
            get {
                return ResourceManager.GetString("pge_Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта.
        /// </summary>
        internal static string pge_Login_UserName {
            get {
                return ResourceManager.GetString("pge_Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя пользователя.
        /// </summary>
        internal static string pge_Login_UserNameRequired {
            get {
                return ResourceManager.GetString("pge_Login_UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким адресом электронной почты не найден. Поищите ошибку или попробуйте другой адрес..
        /// </summary>
        internal static string pg_PwdRecovery_Failed {
            get {
                return ResourceManager.GetString("pg_PwdRecovery_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ваш адрес электронной почты, и мы на него пришлем ваш пароль.
        /// </summary>
        internal static string pg_PwdRecovery_Message {
            get {
                return ResourceManager.GetString("pg_PwdRecovery_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить.
        /// </summary>
        internal static string pg_PwdRecovery_Submit {
            get {
                return ResourceManager.GetString("pg_PwdRecovery_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль выслан вам на электронную почту..
        /// </summary>
        internal static string pg_PwdRecovery_Success {
            get {
                return ResourceManager.GetString("pg_PwdRecovery_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление пароля.
        /// </summary>
        internal static string pg_PwdRecovery_Title {
            get {
                return ResourceManager.GetString("pg_PwdRecovery_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разместить.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет товаров.
        /// </summary>
        internal static string ProductList_NoProducts {
            get {
                return ResourceManager.GetString("ProductList_NoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь увидел страницу без товаров.
        /// </summary>
        internal static string ProductList_NoProducts_Error {
            get {
                return ResourceManager.GetString("ProductList_NoProducts_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте.&lt;br /&gt;&lt;br /&gt;Мы получили запрос на восстановление вашего пароля.&lt;b/&gt;Ваш пароль на сайте: {0}.
        /// </summary>
        internal static string PwdRecovery_Mail_Body {
            get {
                return ResourceManager.GetString("PwdRecovery_Mail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление пароля.
        /// </summary>
        internal static string PwdRecovery_Mail_Subject {
            get {
                return ResourceManager.GetString("PwdRecovery_Mail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия размещения.
        /// </summary>
        internal static string ReadMe {
            get {
                return ResourceManager.GetString("ReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка. Пользователь небыл зарегистрирован..
        /// </summary>
        internal static string Registration_Fail {
            get {
                return ResourceManager.GetString("Registration_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактная информация.
        /// </summary>
        internal static string reg_Contact_info {
            get {
                return ResourceManager.GetString("reg_Contact_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        internal static string role_Admin {
            get {
                return ResourceManager.GetString("role_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        internal static string role_User {
            get {
                return ResourceManager.GetString("role_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить и добавить изображения.
        /// </summary>
        internal static string SaveAndUploadImage {
            get {
                return ResourceManager.GetString("SaveAndUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранено.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по разделам.
        /// </summary>
        internal static string Search_category {
            get {
                return ResourceManager.GetString("Search_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        internal static string Search_Clear {
            get {
                return ResourceManager.GetString("Search_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        internal static string Search_Cost {
            get {
                return ResourceManager.GetString("Search_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширенный поиск.
        /// </summary>
        internal static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать вопрос.
        /// </summary>
        internal static string user_Ask {
            get {
                return ResourceManager.GetString("user_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать вопрос консультанту.
        /// </summary>
        internal static string user_AskConsultant {
            get {
                return ResourceManager.GetString("user_AskConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет.
        /// </summary>
        internal static string user_Cabinet {
            get {
                return ResourceManager.GetString("user_Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои объявления.
        /// </summary>
        internal static string user_Cabinet_EditMy {
            get {
                return ResourceManager.GetString("user_Cabinet_EditMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разместить.
        /// </summary>
        internal static string user_Cabinet_PlaceAd {
            get {
                return ResourceManager.GetString("user_Cabinet_PlaceAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string user_DeleteAd {
            get {
                return ResourceManager.GetString("user_DeleteAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить мои данные.
        /// </summary>
        internal static string user_Edit {
            get {
                return ResourceManager.GetString("user_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string user_EditAd {
            get {
                return ResourceManager.GetString("user_EditAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с логином &apos;{0}&apos; уже существует.
        /// </summary>
        internal static string User_exists {
            get {
                return ResourceManager.GetString("User_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string user_Profile {
            get {
                return ResourceManager.GetString("user_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия размещения.
        /// </summary>
        internal static string Uslovia {
            get {
                return ResourceManager.GetString("Uslovia", resourceCulture);
            }
        }
    }
}
