<?xml version="1.0" encoding="utf-8"?><Database Name="InstantStore" Class="InstantStoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\Projects;Initial Catalog=InstantStore;Integrated Security=True;Connect Timeout=30" SettingsObjectName="InstantStore.Domain.Properties.Settings" SettingsPropertyName="InstantStoreConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ProductSize" Member="ProductSizes">
    <Type Name="ProductSize">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ProductSize_Product" Member="Products" ThisKey="Id" OtherKey="ProductSizeID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.ProductsCategories" Member="ProductsCategories">
    <Type Name="ProductsCategory">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_ProductsCategory" Member="Product" ThisKey="ProductId" OtherKey="ProductId" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="ProductCategory_ProductsCategory" Member="ProductCategory" ThisKey="ProductCategoryID" OtherKey="ProductCategoryId" Type="ProductCategory" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PriceCash" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="PriceCashless" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="ProductSizeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_ProductsCategory" Member="ProductsCategories" ThisKey="ProductId" OtherKey="ProductId" Type="ProductsCategory" />
      <Association Name="ProductSize_Product" Member="ProductSize" ThisKey="ProductSizeID" OtherKey="Id" Type="ProductSize" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductCategories" Member="ProductCategories">
    <Type Name="ProductCategory">
      <Column Name="ProductCategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ParentCategory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisplayType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsVisibleInMenu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="URLAlias" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ProductCategory_ProductsCategory" Member="ProductsCategories" ThisKey="ProductCategoryId" OtherKey="ProductCategoryID" Type="ProductsCategory" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Setting">
      <Column Name="MainDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HeaderHtml" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FooterHtml" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Feedback" Member="Feedbacks">
    <Type Name="Feedback">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Phonenumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsActivated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBlocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPaymentCash" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DefaultCurrencyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ErrorLog" Member="ErrorLogs">
    <Type Name="ErrorLog">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ExceptionText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SessionId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RequestUrl" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ClientIP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserAgent" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ParentCategoryId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShowInMenu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ListType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Attachment" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>